### ISSUE TITLE
Incompatible string formator for python versions below 3.12 

### ISSUE THREAD

**Issue by ushergodwin** [EmmanuelObua/pyload#3]
### Incompatible string formator for Python versions below 3.12 
- Line 124 in loader.py uses an f string formator with a character escape sequence not supported by python versions below 3.12 
```
 command = f"mysql --local-infile -h {env['MYSQL_HOST']} -u {env['MYSQL_USER_NAME']} -p -D {env['MYSQL_DATABASE']} -e \"LOAD DATA LOCAL INFILE '{cleaned_file_path.replace('\\', '\\\\')}' INTO TABLE {table_name} FIELDS TERMINATED BY ',' LINES TERMINATED BY '\\n';\""

``` 

- The below fix works for version < 3.12, tested on python version 3.11.5 
``` 
    cleaned_file_path = cleaned_file_path.replace('\\', '\\\\')
    command = f"mysql --local-infile -h {env['MYSQL_HOST']} -u {env['MYSQL_USER_NAME']} -p -D {env['MYSQL_DATABASE']} -e \"LOAD DATA LOCAL INFILE '{cleaned_file_path}' INTO TABLE {table_name} FIELDS TERMINATED BY ',' LINES TERMINATED BY '\\n';\""

```

**Comment by ushergodwin** [comment]
- @EmmanuelObua  see the error screenshot below 
<img width="1136" alt="Screenshot 2024-01-10 at 13 53 36" src="https://github.com/EmmanuelObua/pyload/assets/65310616/f6bb2778-4b08-4c11-91d6-ee6065f898f3">

**Comment by EmmanuelObua** [comment]
Fixed this issue
